# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:16
    environment:
      TZ: UTC
      POSTGRES_PASSWORD: cheolcheol
    ports:
      - 5432:5432
  # redis fork
  valkey:
    image: valkey/valkey:7
    ports:
      - 6379:6379
